- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  # - Bagel
  - Barratry
<<<<<<< HEAD
  - FireBox
  - Meinhoff
=======
  - Box
>>>>>>> 79f661836f45e6f28d79b64803e96032b62e787b
  - Cluster
  - Fland
  - Kettle
  - Marathon
  - Meta
  - Moose
  - Omega
  - Origin
  - Saltern
