- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  # - Bagel
  - Barratry
  - FireBox
  - Meinhoff
  - Cluster
  - Fland
  - Kettle
  - Marathon
  - Meta
  - Moose
  - Omega
  - Origin
  - Saltern
